### PR TITLE
add ClearVUE.Business

### PR DESCRIPTION
**Pull request by alvzk**
added a new company (lines 955-967) with another company offering IT jobs in the carbon offsetting sector

- [x] I read [CONTRIBUTING.md](https://github.com/pogopaule/awesome-sustainability-jobs/blob/main/CONTRIBUTING.md)  
- [x] I didn't change README.md (but instead src/data.yaml or src/template.md)

### CODE REVIEW

**Review by alvzk — COMMENTED** [review]
Hi. I have updated the UK list with 1 more tool. The preview of changes looks to be working fine for me. Can someone review it, please? Thanks!

**Comment by alvzk** [comment]
@pogopaule hi Fabian! Do you need anything else from my end to approve this pull request?

**Comment by pogopaule** [comment]
Hey @alvzk Thanks for your contribution! I was quite busy with other things, so I couldn't look into it until now.

There are two issues before I can merge.
- The coordinates you provide are somewhere in the North Sea. https://www.openstreetmap.org/#map=13/54.9691/1.5946
- The developer jobs on the careers page are in Malta. So could you add an entry for Malta similar to this https://github.com/pogopaule/awesome-sustainability-jobs/blob/main/src/data.yaml#L23-L28? In case the jobs are not in the UK, could you also remove the UK entry?

**Comment by alvzk** [comment]
Thanks Fabian @pogopaule!
You are right, since dev jobs are all in Malta, I've updated to only that location.
Also, I have fixed the coordinates (pointing to Malta now).
Let me know if it works now.
Thanks,
Anton

**Pull request merged**
